version: "3"
services:
  ap:
    build: .
    environment:
      - DATABASE_HOST=db
      - RAILS_ENV=development
    volumes:
      - .:/app
      - /app/bin
      - /app/vendor
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - tutorial:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  tutorial:
